### ISSUE TITLE
Develop Branch Review

### ISSUE THREAD

**Issue by annchemu** [geoflen/iBLIS_UGANDA#23] opened 2017-03-08 08:15 UTC
Good morning,

Some tables seem to be missing from the migration such as specimen_unhls in the UnhlsSpecimen Model and tests table.

This affects the Tests and Reports modules in the system

**Comment by ereng** [comment] 2017-03-08 09:13
done a little fix up there, @annchemu kindly keep the comments coming, we could keep this issue open for the moment.

**Comment by ereng** [comment] 2017-03-08 09:59
anyone following up on this, remember to adjust database configs of your local machine and run `composer dumpautoload`

**Comment by ereng** [comment] 2017-03-08 11:02
There is a duplicate of models UnhlsTest and Test, fixing now...

**Comment by ereng** [comment] 2017-03-08 11:05
Start test is failing because of confusing the two

**Comment by ereng** [comment] 2017-03-08 11:10
Edit results failing `Class TestController does not exist`

**Comment by ereng** [comment] 2017-03-08 11:53
Am closing this issue, more specific ones can be created

**Closed as completed by ereng** 2017-03-08 11:53 UTC
Labels: bug
